### ISSUE TITLE
Crear el modelo de entidades del proyecto Biblioteca.

### ISSUE THREAD

**Issue by WebCAZ89** [WebCAZ89/Biblioteca-SharkTeam#11]

**Comment by Yintube** [comment]
Se realizó el diagrama de las Entidades del Dominio en la herramienta WhiteStarUml.

**Comment by Ivanov1380** [comment]
Se realizo el Diagrama De Contexto utilizando utilizando la herramienta draw.io
![DiaGramaDeContextoBiblioteca](https://user-images.githubusercontent.com/90813226/133905984-b7f9bc34-d37e-4cc0-8f84-38ac651cf1ea.jpg)

**Comment by Yintube** [comment]
[Captura Kanban.docx](https://github.com/WebCAZ89/Biblioteca-SharkTeam/files/7190519/Captura.Kanban.docx)

**Comment by Yintube** [comment]
![Diagrama Entidades de Dominio](https://user-images.githubusercontent.com/90879972/133906636-83ba253f-da30-4935-b0c4-f8ad4b07d8d1.png)

**Comment by Yintube** [comment]
Diagrama de Entidades de Dominio con Métodos.
![Diagrama de Enti Dominio 2](https://user-images.githubusercontent.com/90879972/133906716-2a76ac8a-fc2b-4d9c-a76d-a796dafbc02d.png)
